---
title: "South Africa's biodiversity provides benefits to people"
---

------------------------------------------------------------------------

# Biodiversity provides jobs

South Africa's biodiversity provides substantial employment in a range of sectors (established but incomplete). Continued investment in managing and conserving biodiversity is essential so that jobs that depend on biodiversity can continue to increase.

# Healthy ecosystems are essential for water security

Rivers, wetlands and their catchment areas are crucial ecological infrastructure for water security, often complementing built infrastructure, but the benefits from some of these ecosystems are currently compromised by their poor ecological condition (well established). Water security can be improved through integrated management of natural resources in Strategic Water Source Areas as well as other key catchments, including protection and restoration in some cases.

# Water flowing into the sea provides multiple benefits to people

Freshwater flowing from rivers through estuaries into the sea is not wasted, and is essential for coastal and marine food production, livelihoods, tourism and future climate change resilience (established but incomplete). Through appropriate management, South Africa can maintain the vital freshwater flows that reach the coast.

# Small high-value ecosystem types take up just 5% of South Africa's territory, but provide disproportionate benefits to people

Certain small ecosystem types function as crucial ecological infrastructure and, despite their small footprint, provide multiple benefits to society (established but incomplete). Managing, protecting and restoring these small, high-value.

# Benefits from fishing are at risk, including food and job security

Estuarine and marine ecosystems provide South Africans with food and livelihoods by providing a basis for fishing -- whether commercial, subsistence or recreational. Yet many fish stocks are overexploited and many fish species are threatened (well established). While a range of plans are in place to ensure that fisheries are sustainable, better practices to rebuild stocks of priority species are needed, as well as reliable data and sufficient capacity for undertaking regular stock assessments.

# Climate change is impacting on people and ecosystems; in spite of this, healthy ecosystems can help us adapt to climate change

The impacts of climate change are evident across all realms and within most species groups. Biodiversity provides resilience against the worst effects of climate change (*established but incomplete*). Restoring ecosystems and maintaining them in a good ecological condition means they are better able to support natural adaptation and mitigation processes, offering increased protection to human communities and reducing the economic burden of future climate disasters.
