---
title: South Africa’s biodiversity is under pressure, but solutions are at hand
---

------------------------------------------------------------------------

# Estuaries and wetlands are the most threatened and least protected ecosystems in South Africa

Estuarine and inland wetland ecosystems face many pressures and are highly threatened (*established but incomplete*). The restoration and protection of estuaries and inland wetlands will secure essential benefits and deliver large return on investment.

# Coastal biodiversity assets, including beaches, are at risk

Sixty per cent of coastal ecosystem types are threatened -- a result of the many pressures concentrated on the coast (*well established*). Judicious coastal development that avoids sensitive areas can minimise further damage, maintain ecological infrastructure and reduce climate risks.

# Protected areas: investment success in the ocean and on land

Protected areas have expanded in the ocean and on land, and are a source of pride for South Africans (*well established*). Continued expansion will help to ensure biodiversity conservation, ecological sustainability and even more social and economic benefits from biodiversity.

# Protected areas: providing effective protection for many species

South Africa's protected areas are generally providing good protection for species, as shown by new protection level indicators for species (established but incomplete). The results provide important feedback for protected area expansion strategies and for protected area management.

# Freshwater fishes are the most threatened species group in South Africa

Freshwater fishes are the most threatened of all species groups that have been fully assessed in South Africa, and half of South Africa's freshwater fish species are found nowhere else in the world (established but incomplete). Effective management and conservation strategies to halt the decline and promote recovery of threatened fish species are needed, focussed on the rivers and catchments where these fish occur.

# Trends in threat status show rapid declines in some of South Africa's species, especially freshwater species and butterflies

Changes in species threat status over time were tracked for eight taxonomic groups using the IUCN Red List Index (RLI). Increased extinction risk is evident for most groups, but freshwater species and butterflies, in particular, show a steep decline (*established but incomplete*). For the RLI to be more comprehensive, repeat assessments are required for species in the marine and estuarine realms, and invertebrates in general.

# Areas where pressures are concentrated should be priorities for spatial planning

The spatial distribution of pressures on biodiversity across the landscape and seascape is uneven. Pressure hotspots, where many different pressures converge, require strategic spatial planning and focussed management (*established but incomplete*).

# Biological invasions threaten biodiversity and human wellbeing

Over 100 alien species have a severe impact on South Africa's biodiversity and, in some cases, on human wellbeing (*well established*). Although some successes in the management of biological invasions have been achieved, the adoption of a national strategy for managing biological invasions, improved project-level planning for prevention and management, and enhanced spatially explicit data will greatly increase effectiveness of current efforts.

# Cooperative governance is essential for healthy landscapes and seascapes

Biodiversity patterns and ecological processes are connected in complex ways that cross realms as well as human-constructed boundaries. At the same time, human activities in a range of different sectors that have separate policies and legislation and are separately managed, can impact on the same biodiversity or ecological infrastructure (*established but incomplete*). To deal with this interconnectedness, cooperative governance and cross-sectoral planning and decision making are essential.
