---
title: The NBA stimulates work to address knowledge gaps
---

------------------------------------------------------------------------

# South Africa’s new seamless map of ecosystem types paves the way for improved assessment, planning and monitoring 

Substantial progress made in classifying and mapping ecosystem types seamlessly across all realms has unlocked comprehensive and systematic assessment and planning for all of South Africa’s territory, providing improved information to inform policy and decision making.

# New indicators developed during the NBA 2018 advance South Africa’s ability to report on the status of biodiversity

The collaborative process of undertaking the NBA builds on innovations and advances in the biodiversity sector to produce new techniques and advances in knowledge. In the NBA 2018, several new indicators have been developed to provide a more comprehensive picture of the state of ecosystems and species.

# Evaluation of genetic diversity brings new value to the NBA

Genetic diversity enables species to evolve and adapt within an ever-changing environment. The development of potential genetic diversity indicators for national-level assessments and monitoring has added value to the NBA and South Africa’s international reporting commitments.

# Investment in strategic and collaborative biodiversity monitoring programmes is crucial to inform management and decision making and for biodiversity assessments

Investment in existing and future strategic and cooperative biodiversity monitoring programmes is essential to strengthen our ability to detect and report on trends, plan accordingly and manage effectively.

