project:
  type: website

website:
  reader-mode: false  # Sidebar and other elements visible
  page-navigation: true
  bread-crumbs: false
  back-to-top-navigation: true
  favicon: images/SANBI_logo.png

  sidebar:
    logo: images/SANBI_logo.png
    pinned: true
    align: left
    style: "docked"
    search: true
    title: "Contents"    
    #collapse-level: 1
    tools: 
      - icon: github
        href: https://github.com/NBA2025
      - icon: youtube
        href: https://www.youtube.com/watch?v=K0XvdAFjCGU
      - icon: save
        href: "https://bgis.sanbi.org/Projects/Detail/1233/"
      - icon: globe
        href: https://biodiversityadvisor.sanbi.org/contentmanagement/index?guid=e7c11960-bb9b-4bac-a736-6c6db0e01b42
      - icon: envelope
        href: "mailto:a.skowno@sanbi.org.za; c.poole@sanbi.org.za"

    contents:
      - text: "**Home**" 
        href: NBA resources.qmd

      - title: "**About the NBA**" 
        href: Contents/0. About/1. About the NBA.qmd
        contents:
          - text: "How is NBA used"
            href: Contents/0. About/2. How the NBA is used.qmd
            contents: 
            - text: "NBA input datasets used"
              href: Contents/0. About/2.1 How NBA input datasets are used.qmd
            - text: "Direct links between NBA and MEA indicators"
              href: Contents/0. About/2.2 Direct links between NBA and MEA indicators.qmd 
              
          - text: "Biodiversity profile"      
            href: Contents/0. About/3. Biodiversity profile.qmd 
          - text: "---" 
      
      - section: "**Key messages**"        
        contents: 
          - text: "A - Biodiversity provides benefits to people"
            href: Contents/1. Key messages/A - Biodiversity provides benefits to people.qmd
          - text: "B - South Africa’s biodiversity is under pressure, but solutions are at hand"
            href: Contents/1. Key messages/B - Biodiversity under pressure.qmd
          - text: "C - NBA stimulates work to address knowledge gaps"
            href: Contents/1. Key messages/C - NBA stimulates work to address knowledge gaps.qmd            
          - text: "---" 
      
      - section: "**Integrated findings**"
        contents:
          - section: "National headline indicators"
            href: Contents/2. Integrated findings/Headline indicators/Indicators overview.qmd
            contents: 
              - text: "Ecosystems"
                href: Contents/2. Integrated findings/Headline indicators/Ecosystems.qmd
              - text: "Species"
                href: Contents/2. Integrated findings/Headline indicators/Species.qmd 
              - text: "Genetic diversity"
                href: Contents/2. Integrated findings/Headline indicators/Genetic diversity.qmd
                
          - section: "Pressures on South Africa's biodiversity"
            href: Contents/2. Integrated findings/Pressures/Pressures overview.qmd
            contents: 
              - text: "Pressures on ecosystems"
                href: Contents/2. Integrated findings/Pressures/Pressures on ecosystems.qmd
              - text: "Pressures on species"
                href: Contents/2. Integrated findings/Pressures/Pressures on species.qmd
              - text: "Ecological condition"
                href: Contents/2. Integrated findings/Pressures/Ecological condition.qmd
          - text: "---" 
      
      - section: "**Findings by realm**"
        contents: 
          - section: "Terrestrial realm"
            href: Contents/3. Findings by realm/1. Terrestrial/0. Terrestrial overview.qmd      
            contents: 
            - text: "Ecosystems "
              href: Contents/3. Findings by realm/1. Terrestrial/1. Terrestrial ecosystems.qmd
            - text: "Ecological condition"
              href: Contents/3. Findings by realm/1. Terrestrial/2. Ecological condition.qmd
            - text: "Red List of ecosystems"
              href: Contents/3. Findings by realm/1. Terrestrial/3. Terrestrial RLE.qmd
            - text: "Protection level"
              href: Contents/3. Findings by realm/1. Terrestrial/4. Terrestrial PL.qmd
            - text: "Species"
              href: Contents/3. Findings by realm/1. Terrestrial/5. Terrestrial species.qmd
              
              
          - section: "Freshwater (inland aquatic) realm"
            href: Contents/3. Findings by realm/2. Freshwater/0. Freshwater overview.qmd
            contents: 
            - text: "Ecosystems "
              href: Contents/3. Findings by realm/2. Freshwater/1. Freshwater ecosystems.qmd
            - text: "Ecological condition"
              href: Contents/3. Findings by realm/2. Freshwater/2. Ecological condition.qmd
            - text: "Red List of ecosystems"
              href: Contents/3. Findings by realm/2. Freshwater/3. Freshwater RLE.qmd
            - text: "Protection level"
              href: Contents/3. Findings by realm/2. Freshwater/4. Freshwater PL.qmd
            - text: "Species"
              href: Contents/3. Findings by realm/2. Freshwater/5. Freshwater species.qmd 
              
              
          - section: "Estuarine realm"
            href: Contents/3. Findings by realm/3. Estuarine/0. Estuarine overview.qmd
            contents: 
            - text: "Ecosystems "
              href: Contents/3. Findings by realm/3. Estuarine/1. Estuarine ecosystems.qmd
            - text: "Ecological condition"
              href: Contents/3. Findings by realm/3. Estuarine/2. Ecological condition.qmd
            - text: "Red List of ecosystems"
              href: Contents/3. Findings by realm/3. Estuarine/3. Estuarine RLE.qmd
            - text: "Protection level"
              href: Contents/3. Findings by realm/3. Estuarine/4. Estuarine PL.qmd
            - text: "Species"
              href: Contents/3. Findings by realm/3. Estuarine/5. Estuarine species.qmd  
    
              
          - section: "Marine realm"
            href: Contents/3. Findings by realm/4. Marine/0. Marine  overview.qmd
            contents: 
            - text: "Ecosystems "
              href: Contents/3. Findings by realm/4. Marine/1. Marine  ecosystems.qmd
            - text: "Ecological condition"
              href: Contents/3. Findings by realm/4. Marine/2. Marine ecological condition.qmd
            - text: "Red List of ecosystems"
              href: Contents/3. Findings by realm/4. Marine/3. Marine RLE.qmd
            - text: "Protection level"
              href: Contents/3. Findings by realm/4. Marine/4. Marine PL.qmd
            - text: "Species"
              href: Contents/3. Findings by realm/4. Marine/5. Marine species.qmd 
              
          - section: "Coast cross-cutting realm"
            href: Contents/3. Findings by realm/5. Coast/0. Coast overview.qmd
            contents: 
            - text: "Ecosystems "
              href: Contents/3. Findings by realm/5. Coast/1. Coast ecosystems.qmd
            - text: "Ecological condition"
              href: Contents/3. Findings by realm/5. Coast/2. Ecological condition.qmd
            - text: "Red List of ecosystems"
              href: Contents/3. Findings by realm/5. Coast/3. Coast RLE.qmd
            - text: "Protection level"
              href: Contents/3. Findings by realm/5. Coast/4. Coast PL.qmd
            - text: "Species"
              href: Contents/3. Findings by realm/5. Coast/5. Coast species.qmd               
            - text: "---" 
      
      - section: "**Species**"
        contents: 
          - text: "Amphibians"
            href: Contents/4. Species/1. Amphibians/Amphibians.qmd
          - text: "Birds"
            href: Contents/4. Species/2. Birds/Birds.qmd
          - text: "Fish" 
            href: Contents/4. Species/3. Fish/Fish.qmd
          
          - section: "Inveterbrates"
            contents: 
            - text: "Bees"
              href: Contents/4. Species/4. Invertebrates/Bees.qmd
            - text: "Branchiopoda"
              href: Contents/4. Species/4. Invertebrates/Branchiopoda.qmd
            - text: "Butterflies"
              href: Contents/4. Species/4. Invertebrates/Butterflies.qmd
            - text: "Crabs"
              href: Contents/4. Species/4. Invertebrates/Crabs.qmd
            - text: "Dragonflies"
              href: Contents/4. Species/4. Invertebrates/Dragonflies.qmd
            - text: "Mollusca"
              href: Contents/4. Species/4. Invertebrates/Mollusca.qmd
            - text: "Spiders"
              href: Contents/4. Species/4. Invertebrates/Spiders.qmd  
              
          - text: "Mammals" 
            href: Contents/4. Species/5. Mammals/Mammals.qmd  
          - text: "Plants" 
            href: Contents/4. Species/6. Plants/Plants.qmd   
          - text: "Reptiles" 
            href: Contents/4. Species/7. Reptiles/Reptiles.qmd                  
          - text: "---" 
      
      - section: "**Priority actions & responses**"
        contents: 
          - section: "Priority actions for improving future NBAs"
            contents:
              - text: "Knowledge gaps and research priorities for strengthening the NBA"
                href: Contents/5. Priority actions and responses/Priority actions/Knowledge gaps.qmd
              - text: "Review of tools used to measure genetic diversity"
                href: Contents/5. Priority actions and responses/Priority actions/Genetic diversity.qmd
            
          - section: "Responses for managing and conserving biodiversity"
            contents:
              - text: "Avoid further loss"
                href: Contents/5. Priority actions and responses/Priority responses/Avoid loss.qmd
              - text: "Protect"
                href: Contents/5. Priority actions and responses/Priority responses/Protect.qmd
              - text: "Restore"
                href: Contents/5. Priority actions and responses/Priority responses/Restore.qmd
              - text: "Resources for biodiversity conservation"
                href: Contents/5. Priority actions and responses/Priority responses/Bio conservation.qmd  
              - text: "evidence on the effectiveness and impact of responses"
                href: Contents/5. Priority actions and responses/Priority responses/Effectiveness impact.qmd    
            
            
            
format:
  html:
    number-sections: true
    number-depth: 6
    page-navigation: true
    embed-resources: true  # ensures that images, CSS, JavaScript, and other resources are embedded directly into the output HTML file
    anchor-sections: true # adds clickable anchors (links) to each section heading in your HTML output, allows users to easily copy a direct link to specific sections, making navigation and sharing more convenient
    toc: true
    linestretch: 1.9
    code-copy: true
    code-overflow: wrap
    css: styles.css
    smooth-scroll: true
    theme:
      light: cosmo
    grid:
      sidebar-width: 350px
      body-width: 1200px
      margin-width: 400px
        
crossref:
  fig-title: '**Figure**'
  fig-labels: arabic
  title-delim: "**:**"
  
execute:
  warning: false
  message: false  

  
page-footer:
  left: |
   [![](/images/SANBI_logo.png){width=200px}](https://www.sanbi.org/)

   center: |
    Made with [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=80px}]

   right: |
    [![](/images/logo-environmental-affairs.jpg){width=200px}](https://www.dffe.gov.za/reports)   

freeze: true

editor: visual

