---
title: "South Africa’s biodiversity profile"
---

-----------------------------------------------------------------------

# Overview of South Africa's biodiversity profile

South Africa has exceptional biodiversity, characterised by high species richness, high levels of species endemism and a wide variety of ecosystems. South Africa's diversity and richness are not limited to biodiversity. Within its borders are also diverse cultures and languages, and exceptional geological and climatic diversity.

Identified as one of the world's 17 megadiverse nations, South Africa ranks as one of the top ten nations globally for plant species richness and third for marine species endemism. With a landmass of 1.2 million km2 and surrounding seas of 1.1 million km2, South Africa is among the smaller of the world's megadiverse countries -- which together contain more than two-thirds of the world's biodiversity. South Africa also holds three of the world's 35 biodiversity hotspots (a measure of biological diversity combined with vulnerability to threats): the Cape Floristic Region, Succulent Karoo biome, and the Maputaland--Pondoland--Albany centre of endemism.


# Biodiversity benefits

Add text

## Benefits of biodiversity in this realm?

### Terrestrial realm

Add text

### Freshwater (inland aquatic) realm

Add text

### Estuarine realm

Add text

### Marine realm

Add text

### Coast cross-cutting realm

Add text
