---
title: "Ecological condition"
sidebar: true
---

------------------------------------------------------------------------

# Overview

Ecological condition is estimated using a range of different approaches across the realms, but essentially depends on the ability to spatially represent the various pressures exerted on biodiversity. Ecological condition in the terrestrial realm relies primarily on land cover change data; cumulative pressure mapping is used in the marine realm; and a multi-criteria ecological condition framework is used in the estuarine and inland aquatic realms. The different systems were aligned as far as possible in the NBA to allow for crossrealm comparisons and unified terminology.

The marine and terrestrial realms are similar in terms of their relatively high percentage of natural/near-natural ecosystem extent (± 80%). In these extensive realms, ecosystem modification tends to be focussed in pressure hotspots, usually linked to regional characteristics such as high productivity, accessibility and valuable natural resources; while large areas remain relatively unmodified or intact. For example, the Cape lowlands have extensive winter field crops while the mountainous areas of the Cape see far less intensive agriculture; all bay ecosystem types, the shelf edge and the KwaZulu-Natal Bight are subject to multiple pressures while many deep sea ecosystems

## Ecological condition per realm

add text

### Terrestrial realm

add text

### Freshwater (inland aquatic) realm

add text

### Estuarine realm

add text

### Marine realm

add text

### Coast cross-realm

add text
